plugins:
  - stylelint-order
  - stylelint-scss

extends:
  - stylelint-config-standard

rules:
  at-rule-no-unknown: null
  function-name-case: ["lower", ignoreFunctions: ['/^[a-z]+(?:[A-Z][a-z]+)*$/']]
  order/properties-alphabetical-order: true
  scss/at-rule-no-unknown: true
