on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: "14.3.0"

      - name: Install module dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
